config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"

  root :to => "statics#home"
  get "/statics/help" =>"statics#help" ,:as=>:help_static
  get "/statics/about" =>"statics#about" ,:as=>:about_static
  get "/statics/new" =>"statics#new" , :as => :new_static
  post "/statics" =>"statics#create" , :as => :statics
  get "/statics/show(/:id)" =>"statics#show"               , :as=>:show_static
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin' , to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

  

end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :email, :password
end

app/models/static.rb
class Static < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :name, :password

#   name 属性的存在性与添加长度验证;
    validates :name, presence: true,
                     length: { maximum: 30 }

#   验证 Email 地址的唯一性，不区分大小写;
    validates :email, presence: true
                      # format: { with: VALID_EMAIL_REGEX }
                      # uniqueness: { case_sensitive: false }
#   使用正则表达式验证 Email 格式;
    # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
#	  把 Email 地址转换成全小写形式，确保唯一性
	  before_save { |user| user.email = email.downcase }
    before_save :create_remember_token

#   添加密码,长度验证               
    validates :password, presence: true, length: { minimum: 6 }
#   密码重复验证
#   validates :password_confirmation, presence: true

#    判断sessions_controller.rb中create方法调用authenticate方法，user中输入的密码与数据库中的是否一致 
    def authenticate(password)
    	password == self.password
    end


    private
      def create_remember_token
    	    self.create_remember_token=	SecureRandom.urlsafe_base64
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@session=Session.new
	end

	def create         
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			# redirect_back_or user_path
            redirect_to users_path
       else
       	flash.now[:error] = 'Invalid email/password combination'
       	@session=Session.new
       	render 'new' 
       end
   end

   def delete
   	sign_out 
   	redirect_to root_path
   end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	def home
	end

	def help
	end

	def about
	end

	def create
	   static=Static.new(params[:static])	
	   if static.save then
	   	redirect_to show_static_path
	   else
	   	render "new"
	   end
    end

    def new
	   @static = Static.new
	end

	def show
		@statics=Static.all
		@static = Static.find params[:id] if params[:id]
		# @static = Static.where(id: params[:id]).first
	end

	# def showcontent
	# 	@static=Static.find(params[:id])
	# end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only: [:edit, :update]
  
  def index
    @users=User.page(params[:page]).per(2)
  end

  def new
  	@user=User.new
  end

  def show
    @user=User.find(params[:id])
  end

  def create
# 创建一个新的 user 对象
  @user=User.new(params[:user])
# 如果 user 对象能成功地保存进数据库
    if @user.save 
       sign_in user
       flash[:success] =  '您已经注册成功'
       redirect_to user
    else
  	  render  "new"
       # redirect_to  new_user_path(@user)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

private
    
    def signed_in_user
      unless signed_in?
        store_location
      redirect_to signin_path, notice:"Please sign in." 
    end
end
    def correct_user
      @user =User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token]=user.remember_token
		self.current_user=user
	end

	def signed_in?
		!current_user.nill?
	end

	def current_user=(user)
		@current_user=user		
	end

	def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
    end

    def sign_out
    	self.current_user=nil
    	cookies.delete(:remember_token)
    end
    
    def current_user?
    	user==current_user
    end

    def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
    end
     
    def store_location
    session[:return_to] = request.fullpath
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
        <%= link_to "Help", help_static_path %>
        <%= link_to "About", about_static_path  %>
        <%= link_to "Create new post", new_static_path %>
        <%= link_to 'sign out',:root %>
<%= yield %>

</body>
</html>

app/views/statics/about.html.erb
<p>About</p>

app/views/statics/help.html.erb
<p>Help</p>

app/views/statics/home.html.erb
<h1>Hello , Welcome to Ruby on Rails</h1>
<p>请登录，新用户请注册！</p><br>
  <p>
  	<%= link_to "登录",new_session_path %>
  </p><br>

  <p>
  	<%= link_to "注册帐号", new_user_path %>
</p><br/>

   

 

app/views/statics/new.html.erb
<h1>New Post</h1>
<%= form_for @static do |f| %>
<p>
	标题:
	<%= f.text_field :title %>
</p>
<p>
	内容：<br />
	<%= f.text_area :content %>
</p>
<p>
	<%=submit_tag("保存")%>
</p>
<% end %>

app/views/statics/show.html.erb
<% if @static %>
<%= @static.content %>
<% else %>
<% @statics.each do |static| %>
	<br>
	<%= link_to static.title, show_static_path(static) %>
<% end  %>
	
<% end %>

app/views/users/edit.html.erb
<h1>Update you profile</h1>
<%= form_for @user do |f| %>
<%= render 'shared/error_messages' %>
	<p>
		<%=f.label("帐号:") %>
		<%=f.text_field :name %>
		<p><br/>
	<p>
		<%=f.label("邮箱:") %>
		<%=f.text_field :email %>
		<p><br/>

	<p>
		<%=f.label("密码:")%>
		<%=f.password_field :password %>
		<p><br/>
	<%=f.submit()%>
<%  end %>
<a href="http://gravatar.com/emails">change</a>
 

app/views/users/index.html.erb
<h1>All User</h1>
<%= paginate @users %>
<%= @users.total_pages %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
<% end %>
</ul>

<%= paginate @users, :prev_label =>'上一页', :next_label => '下一页' %>

app/views/users/new.html.erb
<h1>新用户注册</h1>
<b>请输入您的注册信息</b><br>
<b>注意：请务必输入有效的邮箱用于接收激活邮件</b><br>
<%= form_for @user do |f| %>
    <p>
        <%= f.label ("帐号:") %>
        <%=f.text_field :name %>
        </p><br/>
    <p>
	    <%= f.label ("密码:") %>
        <%=f.password_field :password %>
        </p><br/>
    <p>
	    <%= f.label ("邮箱:") %>
	    <%=f.text_field :email %>
        </p><br/>
    <p>
	    <%=f.submit("注册") %>  
        </p><br/>
<% end %>

app/views/users/show.html.erb
<h1>Hello! Welcome  to  Register</h1>
<%=@user.name %><br>
<%= @user.email %>